// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/lembretes": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lembretes"
                ],
                "summary": "listlembretes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Insere os lembretes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lembretes"
                ],
                "summary": "insertlembretes",
                "parameters": [
                    {
                        "description": "struct",
                        "name": "Lembretes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Lembrete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/lembretes/{id}": {
            "put": {
                "description": "Altera os lembretes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lembretes"
                ],
                "summary": "updatelembretes",
                "parameters": [
                    {
                        "description": "struct",
                        "name": "Lembretes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Lembrete"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Lembrete ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Exclui os lembretes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lembretes"
                ],
                "summary": "deletelembretes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lembrete ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/usuario": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "listusuario",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Insere os usuarios",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "insertusuario",
                "parameters": [
                    {
                        "description": "struct",
                        "name": "Usuarios",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Usuario"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/usuario/{id}": {
            "put": {
                "description": "Altera os usuarios",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "updateusuario",
                "parameters": [
                    {
                        "description": "struct",
                        "name": "Usuarios",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Usuario"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Usuario ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta os usuarios",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "deleteusuario\\",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Usuario ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Lembrete": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "usuarioID": {
                    "type": "integer"
                }
            }
        },
        "main.Usuario": {
            "type": "object",
            "properties": {
                "lembretes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Lembrete"
                    }
                },
                "nome": {
                    "type": "string"
                },
                "sobrenome": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
